"""empty message

Revision ID: 0afa2a5b9d0b
Revises: ac0f61eba29a
Create Date: 2024-10-14 08:53:54.489851

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0afa2a5b9d0b"
down_revision: Union[str, None] = "ac0f61eba29a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "info_tasks",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False, comment="Номер задачи"),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="id пользователя"),
        sa.Column("title", sa.TEXT(), nullable=False, comment="Название задачи"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="время создания задачи"),
        sa.Column("completed_at", sa.DateTime(), nullable=False, comment="время закрытия задачи"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("info_tasks")
    # ### end Alembic commands ###
