"""empty message

Revision ID: ac0f61eba29a
Revises:
Create Date: 2024-10-13 15:08:01.366394

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac0f61eba29a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_tasks",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="id пользователя"),
        sa.Column("successful_count", sa.Integer(), nullable=False, comment="Количество успешных выполненых задач"),
        sa.Column("failed_count", sa.Integer(), nullable=False, comment="Количество проваленных задач"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_tasks")
    # ### end Alembic commands ###
