"""empty message

Revision ID: 7d5de9168749
Revises: 
Create Date: 2024-10-14 10:02:27.754836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d5de9168749'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info_tasks',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False, comment='Номер задачи'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='id пользователя'),
    sa.Column('title', sa.TEXT(), nullable=False, comment='Название задачи'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='время создания задачи'),
    sa.Column('completed_at', sa.DateTime(), nullable=False, comment='время закрытия задачи'),
    sa.Column('completion_attempts', sa.Integer(), nullable=False, comment='Попытка завершить задачу'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_tasks',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='id пользователя'),
    sa.Column('successful_count', sa.Integer(), nullable=False, comment='Количество успешных выполненых задач'),
    sa.Column('failed_count', sa.Integer(), nullable=False, comment='Количество проваленных задач'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tasks')
    op.drop_table('info_tasks')
    # ### end Alembic commands ###
